apiVersion: app/v1
kind: Deployment
metadata: 
  name: frontend-deployment
  labels:
    component: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      component: frontend
  template:
    metadata:
      labels:
        component: frontend
spec:
  containers:
    - name: frontend
      image: prasanthrk/frontend
      imagePullPolicy: always
      ports:
        - containerPort: 80
      env:
        - name: VITE_API_URL
          value: backend-load-balancer-service
          name: VITE_SOCKET_URL
          value: backend-load-balancer-service