apiVersion: v1
kind: service
metadata:
  name: postgres-cluster-ip-service
spec:
  selector:
    component: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
