apiVersion: v1
kind: PersistentVolume  # Create a PV
apiVersion: v1
metadata:
  name: postgres-pv-volume    # Sets PV's name
  labels:
    component: postgres
spec:
  storageClassName: manual
  capacity:
    storage:  1Gi  # Sets PV Volume
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mtd/data"  # Sets the volume's path
